### ISSUE TITLE
Bundler dependency

### ISSUE THREAD

**Issue by chiting** [danielpclark/rutie-gem#2]
Hi,

I was wondering if the [dependency](https://github.com/danielpclark/rutie-gem/blob/a25ea2819fe46eb626cd6ce545f4b8402271a4d3/rutie.gemspec#L17) on `bundler ~> 1.16` is still required as I can't see where it's being loaded in the library.
It could be that it's a development dependency but in that case, the latest `bundler` version released is [2.0.1](https://rubygems.org/gems/bundler/versions/2.0.1).

Thanks!

**Comment by danielpclark** [comment]
Thanks for this.
